/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as DemoRouteImport } from './app/demo'
import { Route as DashboardRouteImport } from './app/dashboard'
import { Route as ChooseOrganizationRouteImport } from './app/choose-organization'
import { Route as IndexRouteImport } from './app/index'
import { Route as DashboardSectionRouteImport } from './app/dashboard/$section'
import { Route as AuthStudentLoginRouteImport } from './app/auth/student-login'
import { Route as AuthStudentChangePasswordRouteImport } from './app/auth/student-change-password'
import { Route as AuthResetPasswordRouteImport } from './app/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './app/auth/register'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as DashboardStudentsSuccessRouteImport } from './app/dashboard/students/success'
import { Route as DashboardStudentsNewRouteImport } from './app/dashboard/students/new'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseOrganizationRoute = ChooseOrganizationRouteImport.update({
  id: '/choose-organization',
  path: '/choose-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthStudentLoginRoute = AuthStudentLoginRouteImport.update({
  id: '/auth/student-login',
  path: '/auth/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudentChangePasswordRoute =
  AuthStudentChangePasswordRouteImport.update({
    id: '/auth/student-change-password',
    path: '/auth/student-change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentsSuccessRoute =
  DashboardStudentsSuccessRouteImport.update({
    id: '/students/success',
    path: '/students/success',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentsNewRoute = DashboardStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-organization': typeof ChooseOrganizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student-change-password': typeof AuthStudentChangePasswordRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/students/success': typeof DashboardStudentsSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-organization': typeof ChooseOrganizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student-change-password': typeof AuthStudentChangePasswordRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/students/success': typeof DashboardStudentsSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-organization': typeof ChooseOrganizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student-change-password': typeof AuthStudentChangePasswordRoute
  '/auth/student-login': typeof AuthStudentLoginRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/students/success': typeof DashboardStudentsSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-organization'
    | '/dashboard'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student-change-password'
    | '/auth/student-login'
    | '/dashboard/$section'
    | '/dashboard/students/new'
    | '/dashboard/students/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-organization'
    | '/dashboard'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student-change-password'
    | '/auth/student-login'
    | '/dashboard/$section'
    | '/dashboard/students/new'
    | '/dashboard/students/success'
  id:
    | '__root__'
    | '/'
    | '/choose-organization'
    | '/dashboard'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student-change-password'
    | '/auth/student-login'
    | '/dashboard/$section'
    | '/dashboard/students/new'
    | '/dashboard/students/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseOrganizationRoute: typeof ChooseOrganizationRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthStudentChangePasswordRoute: typeof AuthStudentChangePasswordRoute
  AuthStudentLoginRoute: typeof AuthStudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-organization': {
      id: '/choose-organization'
      path: '/choose-organization'
      fullPath: '/choose-organization'
      preLoaderRoute: typeof ChooseOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/student-login': {
      id: '/auth/student-login'
      path: '/auth/student-login'
      fullPath: '/auth/student-login'
      preLoaderRoute: typeof AuthStudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/student-change-password': {
      id: '/auth/student-change-password'
      path: '/auth/student-change-password'
      fullPath: '/auth/student-change-password'
      preLoaderRoute: typeof AuthStudentChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/students/success': {
      id: '/dashboard/students/success'
      path: '/students/success'
      fullPath: '/dashboard/students/success'
      preLoaderRoute: typeof DashboardStudentsSuccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/new': {
      id: '/dashboard/students/new'
      path: '/students/new'
      fullPath: '/dashboard/students/new'
      preLoaderRoute: typeof DashboardStudentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardStudentsNewRoute: typeof DashboardStudentsNewRoute
  DashboardStudentsSuccessRoute: typeof DashboardStudentsSuccessRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardStudentsNewRoute: DashboardStudentsNewRoute,
  DashboardStudentsSuccessRoute: DashboardStudentsSuccessRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseOrganizationRoute: ChooseOrganizationRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthStudentChangePasswordRoute: AuthStudentChangePasswordRoute,
  AuthStudentLoginRoute: AuthStudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
