export const colors = {
  app: {
    background: 'bg-[#f7fbf8]',
    backgroundHover: 'hover:bg-[#edf9f3]',
    foreground: 'text-[#15313a]',
    foregroundHover: 'hover:text-[#15313a]',
    card: 'bg-white/92',
    border: 'border-[#d8e5df]',
    borderBg: 'bg-[#d8e5df]',
    borderDashed: 'border-[#d8e5df]',
    muted: 'text-[#526a70]',
    mutedLight: 'text-[#60737a]',
    dark: 'bg-[#12343b]',
    darkAlt: 'bg-[#15313a]',
  },
  brand: {
    text: 'text-[#1d6d54]',
    bg: 'bg-[#1d6d54]',
    subtleBg: 'bg-[#edf9f3]',
    badge: 'border border-[#c7e4d7] bg-[#edf9f3] text-[#1d6d54]',
    icon: 'text-[#1d6d54]',
    focusRing: 'focus:ring-[#1d6d54]',
    hoverBg: 'hover:bg-[#edf9f3]',
  },
  success: {
    text: 'text-[#1d6d54]',
    bg: 'bg-[#8bd8bd]',
    subtleBg: 'bg-[#edf9f3]',
    badge: 'border border-[#c7e4d7] bg-[#edf9f3] text-[#1d6d54]',
    icon: 'text-[#1d6d54]',
  },
  warning: {
    text: 'text-[#8a5a16]',
    subtleBg: 'bg-[#fff8df]',
    badge: 'border border-[#eadb9a] bg-[#fff8df] text-[#8a5a16]',
    icon: 'text-[#8a5a16]',
  },
  danger: {
    text: 'text-[#b42318]',
    subtleBg: 'bg-[#fff0ee]',
    badge: 'border border-[#ffd5cf] bg-[#fff0ee] text-[#b42318]',
  },
} as const

export const dashboardColors = {
  page: `schoolhub-page ${colors.app.foreground}`,
  card: `${colors.app.border} ${colors.app.card} shadow-[0_18px_54px_rgba(18,52,59,0.08)]`,
  muted: colors.app.muted,
  panel: `${colors.app.border} ${colors.app.background}`,
  link: `font-semibold ${colors.brand.text}`,
  activeNav: `${colors.brand.subtleBg} ${colors.brand.text}`,
  inactiveNav: `${colors.app.muted} ${colors.app.backgroundHover} ${colors.app.foregroundHover}`,
  tableHeader: `${colors.app.background} ${colors.app.muted}`,
  focusAvatar: `${colors.brand.focusRing} focus:ring-offset-2`,
} as const
